### PR TITLE
chore: resolutions and dependencies cleanup, address CVEs

### PR DESCRIPTION
**Pull request by tomkdgun**
### Description
There are many leftover resolutions/overrides from past fixes that are no longer relevant and necessary after recent changes.
We need to attempt to remove as many manual resolutions as possible to clean up our dependencies.
Some of them are bringing in modules that are no longer in the dependency tree, override newer versions by older or are not aligned with OpenSearch Dashboard 3.8.0 dependencies.
In some cases resolutions were used instead of dependencies/devDependencies, or completely assume that some specific dependencies will be provided by OpenSearch Dashboard.

Changes:
- Cleaning up resolutions/dependencies/devDependencies
- Align with versions used on OpenSearch Dashboard 3.8
- Check CVEs by `yarn audit` and address these possible to fix

Details:

- The npm modules which require uuid 8.x, 9.x or 10.x will work with 11.1.1 without code changes, but setting uuid 14.x in resolutions it's a risk, this is why I've provided a change from 14.x to 11.1.1 as we have on OpenSearch Dashboard.
- removing not need it resolutions which was also introduced not used dependencies. The CVEs were fixed on OpenSearch Dashboard 3.8.0. Most probably resolutions were added in the past to address OpenSearch Dashboard CVEs on plugin level instead of addressing them there
- fix error during cypress run (existing in main): _error TS5011: The common source directory of 'tsconfig.json' is './.cypress/plugins'. The 'rootDir' setting must be explicitly set to this or another path to adjust your output's file layout._ 

Testing:
- `yarn osd bootstrap` with OpenSearch Dashboard 3.8
- `yarn build`
- `yarn test:jest`
 

### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: tsconfig.json [hunk 1]
```diff
@@ -17,6 +17,7 @@
     "jsx": "react",
     "allowJs": true,
     "baseUrl": ".",
+    "rootDir": ".",
```
Comment (RyanL1997) [inline tsconfig.json]: I think the one merged in PR also did the same fix of this. We can drop this. https://github.com/opensearch-project/dashboards-query-workbench/pull/579

**Review by RyanL1997 — APPROVED** [review]
Hi @tomkdgun , thanks for the change.

File: tsconfig.json (hunk 1 above)
Comment (tomkdgun) [reply tsconfig.json]: Done

**Comment by RyanL1997** [comment]
may need more approvals for this cc @TackAdam @ps48

**Review by ps48 — APPROVED** [review]

**Comment by ps48** [comment]
Many thanks @tomkdgun for the contribution!
